// <auto-generated />
using MSSA.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSSA.Model.Migrations
{
    [DbContext(typeof(GDatabaseContext))]
    [Migration("20190831230500_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSSA.Model.Statistics", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Accuracy");

                    b.Property<long>("Draws");

                    b.Property<long>("Losses");

                    b.Property<long>("TotalDamageDealt");

                    b.Property<long>("TotalDistanceTraveled");

                    b.Property<long>("TotalShotsFired");

                    b.Property<long>("Wins");

                    b.HasKey("Username");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("MSSA.Model.Tank", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Health");

                    b.Property<string>("WeaponName");

                    b.HasKey("Username");

                    b.ToTable("Tank");
                });

            modelBuilder.Entity("MSSA.Model.Weapon", b =>
                {
                    b.Property<string>("WeaponName")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Damage");

                    b.Property<string>("TrajectoryType");

                    b.HasKey("WeaponName");

                    b.ToTable("Weapon");
                });
#pragma warning restore 612, 618
        }
    }
}
